CREATE DATABASE CONTACTSDATA
GO
USE CONTACTSDATA
GO

CREATE TABLE CONTACTS(ContactId INT IDENTITY(1,1) PRIMARY KEY,
FirstName Nvarchar(100) NOT NULL,
LastName Nvarchar(100) NOT NULL,
DateofBirth DATE
);
GO
CREATE TABLE EMAIL(EID INT NOT NULL IDENTITY(1,1), ContactId int not null FOREIGN KEY REFERENCES CONTACTS(ContactId),
Email Nvarchar(150));
GO
CREATE TABLE PHONENUMBERS(PID INT NOT NULL IDENTITY(1,1),ContactId int not null FOREIGN KEY REFERENCES CONTACTS(ContactId),
PhoneNumber Nvarchar(100));
GO

INSERT INTO CONTACTS (FirstName, LastName,DateofBirth)
SELECT 'Bill','Drone', '1989-10-10'
UNION ALL
SELECT 'JOE','Straw', '1999-10-29'
GO
INSERT INTO EMAIL (ContactId, Email)
SELECT 1,'agh@ask.com'
UNION ALL
SELECT 1,'ko@ko.com'
UNION ALL
SELECT 2,'GGko@ko.com'
UNION ALL
SELECT 2,'Bo@ko.com'
GO
INSERT INTO PHONENUMBERS (ContactId, PhoneNumber)
SELECT 1,'9874565652'
UNION ALL
SELECT 1,'6547893214'
SELECT 2,'678945123'
UNION ALL
SELECT 2,'654789231'
GO

SELECT * FROM CONTACTS
SELECT * FROM EMAIL
SELECT * FROM PHONENUMBERS
